language: python

# for container-y goodness:
sudo: false

python:
  - "2.7"
  - "3.6"

install:
  - "pip install --upgrade pip setuptools"
  - "pip install -Ue .[test]"

# command to run tests, e.g. python setup.py test
script: coverage run --source coveralls_check,tests -m py.test tests.py

after_success:
  - coveralls

jobs:
  include:

    - stage: coverage
      python: 3.6
      after_success: skip

      # woof woof!
      install: "pip install -Ue ."
      script: "coveralls-check $TRAVIS_COMMIT"

    - stage: release
      python: 3.6
      script: skip
      after_success: skip

      install: "pip install -Ue .[build]"
      deploy:
        provider: pypi
        user: chrisw
        password:
          secure: xx
        on:
          tags: true
          repo: cjw296/coveralls-check
          python: "3.6"
        skip_cleanup: true
        distributions: "sdist bdist_wheel"
